[[redirects]]
  from = "/entah"
  to = "https://blog.wildanfauzy.com/entah"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  from = "/akhirnya-lulus-setelah-tujuh-tahun"
  to = "https://blog.wildanfauzy.com/akhirnya-lulus-setelah-tujuh-tahun"
  status = 200
  force = true
  from = "/gitolol-otaknya-konslet"
  to = "https://blog.wildanfauzy.com/gitolol-otaknya-konslet"
  status = 200
  force = true
  from = "/ketika-token-listrik-habis"
  to = "https://blog.wildanfauzy.com/ketika-token-listrik-habis"
  status = 200
  force = true
  from = "/mengapa"
  to = "https://blog.wildanfauzy.com/mengapa"
  status = 200
  force = true
  from = "/dikejar-deadline"
  to = "https://blog.wildanfauzy.com/dikejar-deadline"
  status = 200
  force = true
  from = "/penghujung-bulan"
  to = "https://blog.wildanfauzy.com/penghujung-bulan"
  status = 200
  force = true
