[[headers]]
  for = "/*"
  [headers.values]
    Feature-Policy = "geolocation 'self';"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "0"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = '''
            default-src 'self';
            style-src 'self' 'nonce-a9d09b55f2b66e00f4d27f8b453003e6';
            img-src 'self'
        '''
    Strict-Transport-Security = '''
	  max-age=63072000;
	  includeSubDomains;
	  preload'''
 
    Permissions-Policy = '''
            accelerometer=(self),
            ambient-light-sensor=(self),
            autoplay=(self),
            camera=(self),
            encrypted-media=(self),
            fullscreen=(self),
            geolocation=(self),
            gyroscope=(self),
            magnetometer=(self),
            microphone=(self),
            midi=(self),
            payment=(self),
            picture-in-picture=(self),
            speaker=(self),
            usb=(self),
            vibrate=(self),
            vr=(self)
        '''
