name: 'the workflow name' # Name of your workflow

on:
  push:
    branches:
      - master # The trigger of the this workflow

jobs:
  build:
    runs-on: ubuntu-latest # Action uses Docker so only Linux is supported
    steps:
      - uses: actions/checkout@v1 # Checkout your triggered branch
      - uses: xmflsct/action-publish-gatsby@v1 # Uses this action to run further steps
        with:
          publishBranch: 'gh-pages' # Not required, default publishing branch is master
          token: ${{ secrets.ACCESS-TOKEN }} # Your personal access token of GitHub, read more below of how to obtain one and keep it safe
          name: 'wilfauzy' # Not required, default to action's maintainer
          email: 'me@wildanfauzy.com' # Not required, default to action's maintainer
